#!/bin/sh

if [ ! -f "$HOME/.ssh/id_ed25519" ]; then
	echo "Generate SSH key"
	ssh-keygen -t ed25519 -f $HOME/.ssh/id_ed25519 -q -N ""
fi

if [ -z "$ZSH" ]; then
	echo "Install Oh My ZSH"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

echo "Install Homebrew dependencies"
brew bundle --global

# 1Password setup
if [ ! -d "$HOME/.config/op" ]; then
	echo "To install the 1Password CLI, follow: https://developer.1password.com/docs/cli/get-started/#sign-in"
	echo "Then run:"
	echo "  op signin"
	echo "  op plugin init gh"
fi

echo "Install Rust"
rustup-init -y -q
source "$HOME/.cargo/env"

COMPLETIONS_DIR=$HOME/.oh-my-zsh/completions
mkdir -p $COMPLETIONS_DIR
rustup completions zsh >$COMPLETIONS_DIR/_rustup
rustup completions zsh cargo >$COMPLETIONS_DIR/_cargo

echo "Terminal profiles will be opened in new windows."
echo "Use Terminal Preferences to set the default afterwards"
for i in $HOME/.config/terminal/*.terminal
do
open $i
done
